### ISSUE TITLE
Change initial state of the program when there is no data

### ISSUE THREAD

**Issue by starry97** [vega/voyager-electron#20]
![image](https://user-images.githubusercontent.com/19985016/28685448-ac6d139c-72bc-11e7-82ae-19782dd6c466.png)
Clicking on change button to change dataset displays a modal, but clicking on any dataset in the modal does not work

**Comment by kanitw** [comment]
I think we should change initial state of the program when there is no data to say 
load some data, Vega-Lite spec or some previous files.

**Comment by kanitw** [comment]
This should be fixed in https://github.com/vega/voyager/pull/546
