### ISSUE TITLE
Test if loading a Vega-Lite spec with data url works

### ISSUE THREAD

**Issue by kanitw** [vega/voyager-electron#22]
I suspect that the url path could be incorrect and we may need to replace relative path with absolute path (with respect to the root url of the files).

**Comment by kanitw** [comment]
Note that we might be affected by this issue in VL: https://github.com/vega/vega-lite/issues/2418

Thus, the way to go is to copy a spec with url in VL to a new folder and copy its data to a new folder too and modify the `url:` to point to data in the same folder.

**Comment by espressoroaster** [comment]
Verified issue and opened #24.
